### PR TITLE
Added a temp work drawing

### PR DESCRIPTION
**Pull request by Br0mmie**
Added a temp work drawing for it to be easier to make it at home

### CODE REVIEW

**Comment by CaptainBobSim** [comment]
This is so awesome!! Thank you!
Is this done in Fusion 360?

**Comment by Br0mmie** [comment]
No its made in Inventor

**Comment by Br0mmie** [comment]
Planning to make a version in Metric Units

**Comment by CaptainBobSim** [comment]
Sounds good! 
It appears flipped, is this intentional?

**Comment by Br0mmie** [comment]
Nah its a mistake on my end

**Pull request merged**
