### PR TITLE
EGT and Small Instrument improvments

### PR DESCRIPTION
**Pull request by Kovinator**
Merry Christmas Trevor! Hope you and your family are good! Your latest radio design video was great! 

First I wanted to tell you I tried to make changes directly to the project through the F360 team access that you gave me access to. Unfortunately, It isn't working for me. I can not copy the files and make new ones. I can not copy-paste components or anything. I can't even write a completely new file or folder or anything. All I have is basically read access.  I do not think it's a permission thing but rather a money thing. I'm not paying a subscription and I think I have to do that in order to work on teams in fusion 360. With the little amount of work I do, I'm not sure it's worth me paying for a subscription. In any event, I'll have to give it some more thought. For now, having read access will work. It still lets me see things that you are working on that have not been pushed to GitHub yet. If I need a source for something I'll contact you to have you export it out for me to GitHub.

Anyways, here are some small updates for you. Lots of improvements/fixes to the simple small instrument version (9g servo). Changed models to accommodate 3mm glass. Somehow the glass thickness was not set right. Changed the led holes from 4 to 2. The reason for this is when mounted in the panel there are clearance issues with the led contacts. I think it will still look good with two LEDs with the smaller diameter instruments. Should be plenty bright enough still.

Added the EGT with a modified decal. Like the fuel decal, I modified the EGT decal to look closer to the Cessna but it still needs some work. Sorry, I'm not good with decals. Work continues on the sliced panels using a bracket system to hold them in place but this is very much a work in progress. 

As a final note, I plan to tackle the davtron clock next if you haven't already.  I'm not sure if I should put a small screen and then use air manager to display it or build it using a display that mobiflight supports. Your thoughts? Thanks again. Hope you have a wonderful new year!

### CODE REVIEW

**Comment by CaptainBobSim** [comment]
Merry Christmas Kovinator! And Happy New Year!

Too bad the F360 is acting up! If there's anything I can do to help with it let me know!
Feel free to create an issue if you need the source for anything.

Decals are a pain, thank you for your work with these!
Do you have the source files to the decals? If not it's no big deal, but if people want to change the gauge numbers/make adjustments it makes it easier.

I'll keep my mitts off the Davtron!
I think some sort of LCD or 7 segment display would be ideal as opposed to a HDMI display.
image
https://www.amazon.com/dp/B0BCWFB5P3/ref=sspa_dk_detail_3?psc=1&pd_rd_i=B0BCWFB5P3&pd_rd_w=f3k6i&content-id=amzn1.sym.88097cb9-5064-44ef-891b-abfacbc1c44b&pf_rd_p=88097cb9-5064-44ef-891b-abfacbc1c44b&pf_rd_r=BCJTBW0E1WGZK7DKKQ1Q&pd_rd_wg=enTxW&pd_rd_r=cf474364-93ec-4515-afb5-8bd9d84b0fd3&s=mp3&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyQzBXQjBNVTgzSEQ2JmVuY3J5cHRlZElkPUEwNjUyMjY2MVRHV0ZIWlNaUUlLOSZlbmNyeXB0ZWRBZElkPUEwMzA2ODEwM0ZHQUdWQkNSRkdGSyZ3aWRnZXROYW1lPXNwX2RldGFpbCZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=
image

The big issue with 7 segment is that MobiFlight only supports numbers, I'm not so sure about lettering for C and F
The displays will likely be too big so some of it will need to be hidden to the left.

Thank you so much Kovinator!! Your help is amazing!

**Comment by Kovinator** [comment]
Happy new year to you! Only decal versions I have are on your GitHub png and pdf format which was taken from thingiverse. For the davtron I’ll look into going the lcd mobiflight route. I agree the 7 segment wouldn’t work but for the 16x2 does mobiflight support letters as well as numbers? I’ll have to do some research I’m also not sure I’ll be able to place the two 16x2 lcd displays together close enough together and I think one by itself is too small we will have to see. I agree lcds would be better if I can make it work. I’ll only go the air manager hdmi route if I run into a wall. On Dec 26, 2022, at 8:37 PM, Trevor Olsen ***@***.***> wrote:﻿
Merged #171 into main.

**Comment by CaptainBobSim** [comment]
Gotcha - Thank you!
If 16x2 isn't enough space 20x4 exists.
image
I have models for both of these - do you have access to my electronics project? 
These work with both letters and numbers and ^*^&(&%^&*)* characters

**Comment by Kovinator** [comment]
I was looking at that last night on Amazon yeah I think the 20x4 would be the best choice in the yellow green instead of the blue. Ofcourse with this display it won’t look exactly like a davtron m803 as the digits will be smaller but I think it will be alright I just want it to function the same. I’ll check to see if I can get the models from you tonight. I’ll let you know. That would be very helpful. Thanks again!On Dec 27, 2022, at 5:05 PM, Trevor Olsen ***@***.***> wrote:﻿
Gotcha - Thank you!
If 16x2 isn't enough space 20x4 exists.

I have models for both of these - do you have access to my electronics project?
These work with both letters and numbers and ^^&(&%^&)* characters

**Comment by CaptainBobSim** [comment]
I added the models temporarily to the GitHub under section 2: https://github.com/CaptainBobSim/The-Cessna-172-Project-V3/tree/main/Section%202%20-%20Component%20Library%20and%20Structure

**Pull request merged**
